### PR TITLE
pass options through to hast2mdast

### PR DESCRIPTION
**Pull request by sethvincent**

### CODE REVIEW

**Comment by wooorm** [comment]
Could you add a test here too? (probably needs two: together with a destination processor, and without).

**Comment by sethvincent** [comment]
Yes, I'll add that.

**Comment by wooorm** [comment]
👍 

I’ve pushed handlers in `hast-util-to-mdast` as v1.1.0, so it should be possible to add useful tests now!

**Comment by sethvincent** [comment]
@wooorm added tests. not sure if it's quite what you're looking for so happy to make changes if needed.

**Comment by wooorm** [comment]
Yup, that’s perfect! 👍

**Pull request merged**
